# Edit this file to set the Messenger's module settings programmatically instead of using the GUI
# This is regular YAML syntax. See http://docs.ansible.com/ansible/YAMLSyntax.html
# You can override these settings with ENV variables. They are commented below.

hostname: "https://f41da403.ngrok.io" # MESSENGER_HOST

applicationID: "1798356430174406" # MESSENGER_APP_ID
accessToken: "EAAZAjmHwzOMYBAEf3fWhZBZCAaAUlnG9E0PyUMArgh7eh1qM8pDMAnoNfZCdvF5Czw7y4RtmJxYGkNCTokrkZCuDyZBJ61YUl7eqUYhHGBfXCgtdTozI7JAY9ajfyWMUZBxkXKmwl1UggKrpHvod4MEbC46yZCGt5ay4hoCWUncZCEZBpuA0d08UT0y0FztoGih5EZD" # MESSENGER_ACCESS_TOKEN
appSecret: "8354373f73c318e681eb4e34985c3611" # MESSENGER_APP_SECRET

verifyToken: "EAAZAjmHwzOMYBAEf3fWhZBZCAaAUlnG9E0PyUMArgh7eh1qM8pDMAnoNfZCdvF5Czw7y4RtmJxYGkNCTokrkZCuDyZBJ61YUl7eqUYhHGBfXCgtdTozI7JAY9ajfyWMUZBxkXKmwl1UggKrpHvod4MEbC46yZCGt5ay4hoCWUncZCEZBpuA0d08UT0y0FztoGih5EZD" # MESSENGER_VERIFY_TOKEN

displayGetStarted: true
# greetingMessage: ""

# https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu
# persistentMenuItems: []

targetAudience: openToAll
# targetAudienceOpenToSome: ""
# targetAudienceCloseToSome: ""

# trustedDomains: []
# autoRespondGetStarted: true

# paymentTesters: []

# chatExtensionHomeUrl: ""
# chatExtensionInTest: true
# chatExtensionShowShareButton: false

enabled: true
